apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-mongo
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer  # Better for multi-AZ clusters
allowVolumeExpansion: true
reclaimPolicy: Retain

# 1. Install aws-ebs-csi-driver from kubernetes sigs 
#    kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.41"
# 2. Configure AWS using cli
#    aws configure 
